### ISSUE TITLE
Exception when using Redis Cache

### ISSUE THREAD

**Issue by sewid** [stepanenko3/nova-cards#5]
Hi there,

first of all - great plugin! 

I use Redis for caching and nova-cards throws an error when showing the cache card:

```
Undefined variable $sizeInBytes
```

In the CacheController, the method `getFileCacheSize()` does not set `$sizeInBytes` when Redis is used (there is a `print_r()`?!), but tries to return the variable.

**Comment by stepanenko3** [comment]
@sewid 
Hi, Redis is not supported at the moment, and print_r got it by accident, it will be fixed in the next version.

Sorry for the inconvenience
