### ISSUE TITLE
PDO::prepare(): Argument #1 ($query) must be of type string, Illuminate\Database\Query\Expression given

### ISSUE THREAD

**Issue by j-shelfwood** [stepanenko3/nova-cards#8]
I'm using Laravel 10; with your latest version.

Trying to load the VersionCard

**Comment by stepanenko3** [comment]
@j-shelfwood, hid
What database do you use?

**Comment by j-shelfwood** [comment]
mysql  Ver 8.0.32 for macos13.0 on x86_64 (Homebrew)

**Comment by stepanenko3** [comment]
@j-shelfwood 
Check the new version, please
If the error persists, share the full trace
Or you can make a pull request, I will be very grateful

**Comment by imnpc** [comment]
in  Laravel 10
src/Http/Controllers/VersionsController.php Line 34

```php
$results =  DB::select("select version()");   // edit this
```
